services:
  mariadb:
    image: mariadb:inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception_net
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always


  wordpress:
    image: wordpress:inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    secrets:
      - db_password
      - credentials
    networks:
      - inception_net
    volumes:
      - wordpress_data:/var/www/html
    restart: always

  nginx:
    image: nginx:inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
      - static_site
      - adminer
      - portainer
    ports:
      - "443:443"
    networks:
      - inception_net
    volumes:
      - wordpress_data:/var/www/html
    restart: always

  redis:
    image: redis:inception
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    container_name: redis
    networks:
      - inception_net
    restart: always

  ftp:
    image: ftp:inception
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    container_name: ftp
    depends_on:
      - wordpress
    env_file:
      - .env
    secrets:
      - ftp_password
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - inception_net
    volumes:
      - wordpress_data:/var/www/html
    restart: always
  
  static_site:
    image: static_site:inception
    build:
      context: ./requirements/bonus/static_site
      dockerfile: Dockerfile
    container_name: static_site
    networks:
      - inception_net
    restart: always

  adminer:
    image: adminer:inception
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    container_name: adminer
    depends_on:
      - mariadb
    expose:
      - "8080"
    networks:
      - inception_net
    restart: always

  portainer:
    image: portainer:inception
    build:
      context: ./requirements/bonus/portainer
      dockerfile: Dockerfile
    container_name: portainer
    expose:
      - "9000"
    networks:
      - inception_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_storage:/data
    restart: always

networks:
  inception_net:
    name: inception_net
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sjoukni/data/mariadb
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sjoukni/data/wordpress
  portainer_storage:
    name: portainer_storage
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sjoukni/data/portainer

secrets:
  credentials:
    file: ../secrets/credentials.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
